# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            voidc
tagline:          blog
url:              http://voidc.github.com
baseurl:          /
author:
  name:           Dominik Stolz
  url:            http://voidc.github.com
